#!/usr/bin/env python3
"""Generate ``src/airscope/campaigns/wps/wps_pindb.py`` from airgeddon and fulvius PIN lists.

Combines:
- airgeddon's known_pins.db (https://github.com/v1s1t0r1sh3r3/airgeddon)
- fulvius31's Default-WPS-PINs pins.csv (https://github.com/fulvius31/Default-WPS-PINs)

Emits:
- OUI_PINS: OUI -> tuple of static factory PINs (700+ entries)
- OUI_ALGOS: OUI -> tuple of known algorithm names (zhao, asus, dlink, dlink1, airocon, etc.)
- MODEL_PINS: Router model -> tuple of default PINs

Usage:
    uv run python scripts/generators/gen_wps_pindb.py
"""
from __future__ import annotations

import re
import urllib.request
from collections import defaultdict
from pathlib import Path

from airscope.dot11.wsc.crypto import pin_checksum

_AIRGEDDON_URL = "https://raw.githubusercontent.com/v1s1t0r1sh3r3/airgeddon/master/known_pins.db"
_FULVIUS_URL = "https://raw.githubusercontent.com/fulvius31/Default-WPS-PINs/main/pins.csv"

OUT_FILE = (Path(__file__).resolve().parents[2]
            / "src" / "airscope" / "campaigns" / "wps" / "wps_pindb.py")

# Recognized algorithm names in fulvius dataset
ALGO_NAME_MAP = {
    "zhao": "zhao",
    "computepin": "zhao",
    "asus": "asus",
    "dlink": "dlink",
    "dlink1": "dlink1",
    "airocon": "airocon",
    "thirtytwo": "computepin_32",
    "twentyeight": "computepin_28",
    "trend": "trendnet",
    "arcady": "arcadyan",
}


def _read_content(local_name: str, url: str) -> str:
    for candidate_dir in (Path("."), Path("scratch"), Path(".data")):
        p = candidate_dir / local_name
        if p.is_file():
            return p.read_text(encoding="utf-8", errors="ignore")
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", "ignore")


def _normalize_pin(raw: str) -> str | None:
    digits = re.sub(r"\D", "", raw)
    if len(digits) == 8:
        return digits
    if len(digits) == 7:
        try:
            seven = int(digits)
            return f"{digits}{pin_checksum(seven)}"
        except ValueError:
            return None
    return None


def load_airgeddon(text: str) -> dict[str, list[str]]:
    oui_pins: dict[str, list[str]] = defaultdict(list)
    for oui, pins_str in re.findall(r'PINDB\["([0-9A-Fa-f]{6})"\]="([^"]+)"', text):
        norm_oui = oui.upper()
        for p in pins_str.split():
            norm_pin = _normalize_pin(p)
            if norm_pin and norm_pin not in oui_pins[norm_oui]:
                oui_pins[norm_oui].append(norm_pin)
    return oui_pins


def load_fulvius(
    text: str, existing_pins: dict[str, list[str]]
) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    oui_algos: dict[str, list[str]] = defaultdict(list)

    for line in text.splitlines():
        line = line.strip()
        if not line or "," not in line:
            continue
        parts = line.split(",")
        item_raw, oui_raw = parts[0].strip().lower(), parts[1].strip()
        oui = re.sub(r"[^0-9A-Fa-f]", "", oui_raw).upper()
        if len(oui) != 6:
            continue

        if item_raw in ALGO_NAME_MAP:
            algo_key = ALGO_NAME_MAP[item_raw]
            if algo_key not in oui_algos[oui]:
                oui_algos[oui].append(algo_key)
        else:
            norm_pin = _normalize_pin(item_raw)
            if norm_pin and norm_pin not in existing_pins[oui]:
                existing_pins[oui].append(norm_pin)

    return existing_pins, oui_algos


def main() -> None:
    air_text = _read_content("known_pins.db", _AIRGEDDON_URL)
    fulv_text = _read_content("pins.csv", _FULVIUS_URL)

    merged_pins = load_airgeddon(air_text)
    merged_pins, oui_algos = load_fulvius(fulv_text, merged_pins)

    total_pins = sum(len(pins) for pins in merged_pins.values())
    total_algo_mappings = sum(len(algos) for algos in oui_algos.values())
    print(f"Loaded {len(merged_pins)} OUIs with static PINs ({total_pins} total PIN entries).")
    print(f"Loaded {len(oui_algos)} OUIs with algorithm mappings ({total_algo_mappings} entries).")

    header = (
        '"""WPS default factory PIN database (OUI and Model mappings).\n\n'
        "GENERATED by scripts/generators/gen_wps_pindb.py from airgeddon and Default-WPS-PINs.\n"
        "Do NOT edit by hand; rerun the generator to refresh.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "# Known specific model factory default PINs (matched via WSC identity / router fingerprint).\n"
        "MODEL_PINS: dict[str, tuple[str, ...]] = {\n"
        '    "DIR-615": ("12345670", "68175542"),\n'
        '    "DIR-645": ("12345670",),\n'
        '    "DSL-2740R": ("68175542",),\n'
        '    "WNR2000": ("12345670",),\n'
        '    "HG532c": ("12345670",),\n'
        '    "TD-W8961ND": ("12345670",),\n'
        '    "TD-W8951ND": ("12345670",),\n'
        "}\n\n"
        "# Empirical OUI -> Algorithm associations (zhao, asus, dlink, dlink1, airocon, etc.).\n"
        "OUI_ALGOS: dict[str, tuple[str, ...]] = {\n"
    )

    body_algos = ""
    for oui in sorted(oui_algos):
        algos = tuple(oui_algos[oui])
        algos_repr = ", ".join(f'"{a}"' for a in algos)
        body_algos += f'    "{oui}": ({algos_repr},),\n' if len(algos) == 1 else f'    "{oui}": ({algos_repr}),\n'

    mid = (
        "}\n\n"
        "# 600+ verified empirical factory default PINs keyed by 24-bit MAC OUI prefix.\n"
        "OUI_PINS: dict[str, tuple[str, ...]] = {\n"
    )

    body_pins = ""
    for oui in sorted(merged_pins):
        pins = tuple(merged_pins[oui])
        pins_repr = ", ".join(f'"{p}"' for p in pins)
        body_pins += f'    "{oui}": ({pins_repr},),\n' if len(pins) == 1 else f'    "{oui}": ({pins_repr}),\n'

    footer = "}\n"

    OUT_FILE.write_text(header + body_algos + mid + body_pins + footer, encoding="utf-8")
    print(f"Wrote database to {OUT_FILE}")


if __name__ == "__main__":
    main()
