"""Extract the RTL8188E phydm init tables from the vendor PHYDM source.

The 8188e config tables are flat-u32 conditional arrays consumed by the phydm
walker (``odm_read_and_config_mp_8188e_*``). This parses each array verbatim
(every ``0x..`` token between ``name[] = {`` and ``};``, in source order) into a
Python module the port's ``phy_cond.walk_table`` consumes 1:1. Conditional
control words are kept inline exactly as the source emits them — the walker, not
this script, resolves them.

    uv run python scripts/chips/rtl8188eus_dkms/extract_tables.py
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
PHYDM = (REPO / "driver_captures" / "captures_8188eu" / "driver-source"
         / "hal" / "phydm" / "rtl8188e")
OUT_DIR = REPO / "src" / "airscope" / "chips" / "rtl8188eus_dkms"

_U32 = re.compile(r"0x[0-9A-Fa-f]+")

# (source .c, array name, output module, python var)
TABLES = [
    ("halhwimg8188e_mac.c", "array_mp_8188e_mac_reg", "mac_reg_tbl.py", "MAC_REG"),
    ("halhwimg8188e_bb.c", "array_mp_8188e_phy_reg", "bb_phy_reg_tbl.py", "PHY_REG"),
    ("halhwimg8188e_bb.c", "array_mp_8188e_agc_tab", "bb_agc_tab_tbl.py", "AGC_TAB"),
    ("halhwimg8188e_bb.c", "array_mp_8188e_phy_reg_pg", "bb_phy_reg_pg_tbl.py", "PHY_REG_PG"),
    ("halhwimg8188e_rf.c", "array_mp_8188e_radioa", "rf_radio_a_tbl.py", "RADIO_A"),
]


def extract_array(text: str, name: str) -> list[int]:
    start = text.index(f"{name}[] = {{")
    body = text[start + text[start:].index("{") + 1:]
    body = body[:body.index("};")]
    return [int(h, 16) for h in _U32.findall(body)]


def emit(values: list[int], var: str, path: Path, src: str, name: str) -> None:
    rows = [f"    {', '.join(f'0x{v:08X}' for v in values[i:i + 6])},"
            for i in range(0, len(values), 6)]
    body = "\n".join(rows)
    path.write_text(
        f'"""RTL8188E phydm init table — extracted verbatim from the vendor source.\n\n'
        f'{var} = {name}[] [SRC] hal/phydm/rtl8188e/{src} ({len(values)} u32).\n'
        f'Generated by scripts/chips/rtl8188eus_dkms/extract_tables.py — do not hand-edit.\n"""\n\n'
        f"{var} = [\n{body}\n]\n",
        encoding="utf-8",
    )


def main() -> int:
    for src, name, out, var in TABLES:
        cpath = PHYDM / src
        text = cpath.read_text(errors="replace")
        try:
            vals = extract_array(text, name)
        except ValueError:
            print(f"SKIP {name}: not found in {src}")
            continue
        emit(vals, var, OUT_DIR / out, src, name)
        print(f"wrote {out}: {var} = {len(vals)} u32 ({name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
