"""Extract rtw8821a init tables from kernel C source to Python data files.

Source: driver_sources/rtw88-source-v6.18/rtw8821a_table.c
Output: src/airscope/chips/rtl8821au/assets/{mac,agc,bb,rf_a}_tbl.py

The four tables (`rtw8821a_mac`, `rtw8821a_agc`, `rtw8821a_bb`, `rtw8821a_rf_a`)
are arrays of u32 in C. Conceptually each table is a sequence of 8-byte
"tiles" — but the array is flat u32s so an IF/ELIF block (which carries a
positive cond + a neg-trigger) takes 4 u32s, while ELSE/ENDIF (no
neg-trigger) take 2 u32s. The runtime walker (chips/rtl8821au/phy_cond.py)
mirrors `rtw_parse_tbl_phy_cond` in phy.c exactly.

We preserve the C order and values 1:1 — no resolution at extract time —
so the data files diff cleanly against future kernel versions.

Usage:
    uv run scripts/chips/rtl8821au/extract_init_tables.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "driver_sources/rtw88-source-v6.18/rtw8821a_table.c"
OUT_DIR = ROOT / "src/airscope/chips/rtl8821au/assets"

TABLES = ("mac", "agc", "bb", "rf_a")


def parse_table(text: str, name: str) -> list[int]:
    """Return the flat u32 list for `static const u32 rtw8821a_<name>[] = { ... };`."""
    pat = re.compile(
        rf"static\s+const\s+u32\s+rtw8821a_{re.escape(name)}\[\]\s*=\s*\{{(.*?)\}}\s*;",
        re.DOTALL,
    )
    m = pat.search(text)
    if not m:
        raise SystemExit(f"rtw8821a_{name} not found in source")
    body = m.group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//.*", "", body)
    return [int(tok, 16) for tok in re.findall(r"0[xX][0-9A-Fa-f]+", body)]


def count_markers(words: list[int]) -> dict[str, int]:
    """Walk tile-by-tile, classify each tile, sanity-check balance."""
    counts = {"cfg": 0, "if": 0, "elif": 0, "else": 0, "endif": 0, "neg": 0}
    i = 0
    n = len(words)
    while i + 1 < n:
        w0 = words[i]
        pos = (w0 >> 31) & 1
        neg = (w0 >> 30) & 1
        if pos:
            branch = (w0 >> 28) & 3
            counts[("if", "elif", "else", "endif")[branch]] += 1
        elif neg:
            counts["neg"] += 1
        else:
            counts["cfg"] += 1
        i += 2
    return counts


HEADER_TMPL = '''"""rtw8821a {name} init table — extracted from kernel rtw8821a_table.c.

Auto-generated by scripts/chips/rtl8821au/extract_init_tables.py — DO NOT EDIT.

Flat u32 list, walked 2 at a time by `chips.rtl8821au.phy_cond`.
{summary}
"""

TABLE: list[int] = [
'''


def emit(name: str, words: list[int]) -> Path:
    counts = count_markers(words)
    summary = (
        f"cfg={counts['cfg']}  IF={counts['if']}  ELIF={counts['elif']}  "
        f"ELSE={counts['else']}  ENDIF={counts['endif']}  neg={counts['neg']}  "
        f"u32s={len(words)}"
    )
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f"{name}_tbl.py"
    lines = [HEADER_TMPL.format(name=name, summary=summary)]
    for k in range(0, len(words), 2):
        a, b = words[k], words[k + 1]
        lines.append(f"    0x{a:08X}, 0x{b:08X},\n")
    lines.append("]\n")
    out.write_text("".join(lines), encoding="utf-8")
    print(f"  {name:5s} -> {out.relative_to(ROOT)}  ({summary})")

    if counts["if"] + counts["elif"] != counts["neg"]:
        print(f"    WARN: IF+ELIF ({counts['if']+counts['elif']}) != neg ({counts['neg']})")
    if counts["if"] != counts["endif"]:
        print(f"    WARN: IF ({counts['if']}) != ENDIF ({counts['endif']})")
    return out


def main() -> int:
    if not SRC.exists():
        print(f"ERROR: missing {SRC}", file=sys.stderr)
        return 1
    text = SRC.read_text(encoding="utf-8", errors="replace")
    print(f"Reading {SRC.relative_to(ROOT)}")
    for name in TABLES:
        words = parse_table(text, name)
        emit(name, words)
    return 0


if __name__ == "__main__":
    sys.exit(main())
