"""Extract the RTL8814AU RF (radio) init tables from the vendor PHYDM source.

`PHY_RF6052_Config_8814A` loads one conditional radio table per RF path A..D
(``array_mp_8814a_radio{a,b,c,d}`` in
``hal/phydm/halrf/rtl8814a/halhwimg8814a_rf.c``) through the same phy_cond walker
as the BB tables. This parses each array verbatim into a Python module the port's
walker consumes 1:1 (conditional control words kept inline).

Run: ``uv run python scripts/chips/rtl8814au_dkms/extract_rf_tables.py``
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
RF_C = (
    REPO / "driver_captures" / "captures_rtl8814au" / "driver-source"
    / "hal" / "phydm" / "halrf" / "rtl8814a" / "halhwimg8814a_rf.c"
)
OUT_DIR = REPO / "src" / "airscope" / "chips" / "rtl8814au_dkms"

_U32 = re.compile(r"0x[0-9A-Fa-f]+")
PATHS = (("a", 124), ("b", 2244), ("c", 4272), ("d", 6344))


def extract_array(text: str, name: str) -> list[int]:
    start = text.index(f"{name}[] = {{")
    body = text[start + text[start:].index("{") + 1:]
    body = body[:body.index("};")]
    return [int(h, 16) for h in _U32.findall(body)]


def emit(values: list[int], path: str, src_line: int) -> None:
    var = f"RADIO_{path.upper()}"
    lines = [f"\t{', '.join(f'0x{v:08X}' for v in values[i:i + 6])},"
             for i in range(0, len(values), 6)]
    body = "\n".join(lines)
    out = OUT_DIR / f"rf_radio_{path}_tbl.py"
    out.write_text(
        f'"""RTL8814AU radio-{path} RF init table - extracted 1:1 from vendor PHYDM source.\n\n'
        f"``array_mp_8814a_radio{path}`` [SRC halhwimg8814a_rf.c:{src_line}],\n"
        f"{len(values)} u32 in source order (conditional control words kept inline;\n"
        f'the phy_cond walker in ``rf.py`` resolves them). Generated by\n'
        f'``scripts/chips/rtl8814au_dkms/extract_rf_tables.py`` - do not hand-edit.\n"""\n'
        f"from __future__ import annotations\n\n"
        f"{var} = (\n{body}\n)\n",
        encoding="utf-8",
    )
    print(f"  wrote {len(values)} u32 -> {out.relative_to(REPO)}")


def main() -> int:
    text = RF_C.read_text()
    for path, line in PATHS:
        values = extract_array(text, f"array_mp_8814a_radio{path}")
        emit(values, path, line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
