"""Extract the RTL8814AU BB init tables from the vendor PHYDM source.

`PHY_BBConfig8814` loads two flat-u32 conditional tables through the phydm walker:
``array_mp_8814a_phy_reg`` (PHY_REG) and ``array_mp_8814a_agc_tab`` (AGC_TAB),
both in ``hal/phydm/rtl8814a/halhwimg8814a_bb.c``. This parses each array verbatim
(every ``0x..`` token between ``name[] = {`` and ``};``, in source order) into a
Python module the port's walker consumes 1:1. Conditional control words are kept
inline exactly as the source emits them — the walker, not this script, resolves
them.

Run: ``uv run python scripts/chips/rtl8814au_dkms/extract_bb_tables.py``
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
BB_C = (
    REPO / "driver_captures" / "captures_rtl8814au" / "driver-source"
    / "hal" / "phydm" / "rtl8814a" / "halhwimg8814a_bb.c"
)
OUT_DIR = REPO / "src" / "airscope" / "chips" / "rtl8814au_dkms"

_U32 = re.compile(r"0x[0-9A-Fa-f]+")


def extract_array(text: str, name: str) -> list[int]:
    start = text.index(f"{name}[] = {{")
    body = text[start + text[start:].index("{") + 1:]
    body = body[:body.index("};")]
    return [int(h, 16) for h in _U32.findall(body)]


def emit(values: list[int], var: str, path: Path, src_line: int) -> None:
    lines = [f"\t{', '.join(f'0x{v:08X}' for v in values[i:i + 6])},"
             for i in range(0, len(values), 6)]
    body = "\n".join(lines)
    path.write_text(
        f'"""RTL8814AU {var} BB init table - extracted 1:1 from vendor PHYDM source.\n\n'
        f"``array_mp_8814a_{var.lower()}`` [SRC halhwimg8814a_bb.c:{src_line}],\n"
        f"{len(values)} u32 in source order (conditional control words kept inline;\n"
        f'the phy_cond walker in ``bb.py`` resolves them). Generated by\n'
        f'``scripts/chips/rtl8814au_dkms/extract_bb_tables.py`` - do not hand-edit.\n"""\n'
        f"from __future__ import annotations\n\n"
        f"{var} = (\n{body}\n)\n",
        encoding="utf-8",
    )
    print(f"  wrote {len(values)} u32 -> {path.relative_to(REPO)}")


def main() -> int:
    text = BB_C.read_text()
    phy_reg = extract_array(text, "array_mp_8814a_phy_reg")
    agc_tab = extract_array(text, "array_mp_8814a_agc_tab")
    print(f"phy_reg: {len(phy_reg)} u32 | agc_tab: {len(agc_tab)} u32")
    emit(phy_reg, "PHY_REG", OUT_DIR / "bb_phy_reg_tbl.py", 3274)
    emit(agc_tab, "AGC_TAB", OUT_DIR / "bb_agc_tab_tbl.py", 112)
    return 0


if __name__ == "__main__":
    sys.exit(main())
